#!/bin/bash
#
# by Jama Ariai (jama.ariai@oc.jlug.de)
# calculation of the radius of gyration (=gyradius)
# Gyradius = RMSD between Center of Mass and every Atom
#
# Syntax: calcGyradius [FILE]
# Output: Radius of Gyration
#

unset SUFFIX XYZFILE checkline Atom X Y Z squaredDISTANCE GYRADIUS

PATHSCRIPTS=$(dirname $0)
FILE=$1

while getopts "h" OPTION
do
    case $OPTION in
		h)
			cat "$PATHSCRIPTS/help_calcGyradius.txt" 
#			echo "Help-File does not exist (yet)".
			exit 10
		;;
		*)
			echo -e "Nonexistent flag.\033[31m Aborting.\033[0m"
			exit 10
		;;
    esac
done

#echo "Input-File: $FILE"
if [ ! -f $FILE ]; then echo -e "\033[31mInput-File does not exist! Aborting.\033[0m"; exit 128; fi 
SUFFIX=$(echo $FILE | rev | cut -f1 -d'.' | rev)

################### valid formats: XYZ and OUT
case $SUFFIX in
	xyz)	XYZFILE=$FILE
	;;
	out)	out2xyz $FILE
			XYZFILE=$(echo $FILE | sed 's/.out/.xyz/')
    ;;
	\?) 	echo -e "\033[31mInvalid Input-Format! Aborting.\033[0m"; exit 10
	;;
esac

numAtom=0		### counts the number of atoms
sumMass=0		### sum of the molecular mass
sumX=0			### summed x-components weighted by mass
sumY=0			### summed y-components weighted by mass
sumZ=0			### summed z-components weighted by mass
sumsqDistance=0	### summed squared-Distance from each Atom to the Center of Mass

maxlines=$(wc -l $XYZFILE | awk '{print $1}')
re1='^\s*[a-zA-Z]{1,2}(\s+[-]?[0-9]*\.[0-9]*){3}\s*$'
re2='^\s*[0-9]{1,3}(\s+[-]?[0-9]*\.[0-9]*){3}\s*$'
#echo "maxlines: $maxlines"
for (( i=1 ; i <= $maxlines ; i++ )); do	# loop over all entries of XYZFILE
	checkline=$(sed -n "$i"p $XYZFILE)
#	echo "check line by regex: $checkline"
	if [[ $checkline =~ $re1 ]] || [[ $checkline =~ $re2 ]]; then ### check if given line contains atomic coordinates
#		echo "valid line: $i"
		((numAtom++))
		Atom[$i]=$(sed -n "$i"p $XYZFILE | awk '{print $1}')
		X[$i]=$(sed -n "$i"p $XYZFILE | awk '{print $2}')
		Y[$i]=$(sed -n "$i"p $XYZFILE | awk '{print $3}')
		Z[$i]=$(sed -n "$i"p $XYZFILE | awk '{print $4}')
		Mass[$i]=$(convertPTE -W ${Atom[$i]})
		sumMass=$(echo "$sumMass+${Mass[$i]}" | bc -l)
		sumX=$(echo "$sumX+(${Mass[$i]}*${X[$i]})" | bc -l)
		sumY=$(echo "$sumY+(${Mass[$i]}*${Y[$i]})" | bc -l)
		sumZ=$(echo "$sumZ+(${Mass[$i]}*${Z[$i]})" | bc -l)
	fi
done
#echo "Summation done

if [[ "$numAtom" = 0 ]] || [[ "$sumMass" = 0 ]]; then echo -e "\033[31mCalculation of Center of Mass failed! Aborting.\033[0m"; exit 10; fi

X_COM=$(echo "$sumX/$sumMass" | bc -l)
Y_COM=$(echo "$sumY/$sumMass" | bc -l)
Z_COM=$(echo "$sumZ/$sumMass" | bc -l)


for (( i=1 ; i <= $maxlines ; i++ )); do
#echo "loop: $i"
	if ! [[ -z "${Atom[$i]}" ]]; then
#		echo "Calculate distance for ${Atom[$i]}"
		squaredDISTANCE[$i]=$(echo "((${X[$i]}-$X_COM)^2)+((${Y[$i]}-$Y_COM)^2)+((${Z[$i]}-$Z_COM)^2)" | sed 's/--/+/g' | bc -l)
		sumsqDistance=$(echo "$sumsqDistance+${squaredDISTANCE[$i]}" | bc -l)
	fi
done

GYRADIUS=$(echo "sqrt($sumsqDistance/$numAtom)" | bc -l | xargs printf "%.*f\n" 6)

#### OUTPUT
echo -e "Number of atoms: $numAtom\nMolecular Mass in amu: $sumMass\nCenter of Mass: ($X_COM,$Y_COM,$Z_COM)"
echo "Radius of Gyration (in Ang): $GYRADIUS"
# echo "Sum of mass-weighted components (x,y,z): ($sumX,$sumY,$sumZ)"


